[package]
name = "in"
version = "1.0.1"
edition = "2021"
authors = ["Jay Churchill"]
license = "MIT"
description = "Python's input() for Rust"
documentation = "https://docs.rs/in"
repository = "https://github.com/rtificr/input"
homepage = "https://github.com/rtificr/input"

[dependencies]
