[package]
name = "in"
version = "1.0.0"
edition = "2021"
authors = ["Jay Churchill"]
license = "MIT"
description = "Simple input macros like println!"
documentation = "https://docs.rs/in"
repository = "https://github.com/rtificr/input"
homepage = "https://github.com/rtificr/input"

[dependencies]
